version: 2

grow_install: &grow_install
    name: Grow Intall
    command: grow install

grow_build: &grow_build
    name: Grow Build
    command: grow build

jobs:
  build:
    working_directory: ~/grow
    docker:
      - image: grow/base:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - &cache_key grow-cache-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: *grow_install
      - save_cache:
          key: *cache_key
          paths:
          - node_modules
      - run: *grow_build

  cache_free:
    working_directory: ~/grow
    docker:
    - image: grow/base:latest
    steps:
    - checkout
    - run: *grow_install
    - run: *grow_build

workflows:
  version: 2

  build:
    jobs:
    - build
  weekly:
    triggers:
    - schedule:
        cron: "0 0 * * 0"
        filters:
          branches:
            only:
            - master
    jobs:
    - cache_free
